import './globals.css';

import Theinhardt from 'next/font/local';

const theinhardt = Theinhardt({
  variable: '--font-sans',
  display: 'swap',
  src: [
    {
      path: '/fonts/Theinhardt/Theinhardt-Medium.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '/fonts/Theinhardt/Theinhardt-Medium-Italic.otf',
      weight: '400',
      style: 'italic',
    },
  ],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={theinhardt.variable}>
      <body>{children}</body>
    </html>
  );
}
